"""Add email verification fields

Revision ID: f5830da0142f
Revises: 
Create Date: 2025-11-28 12:13:27.369432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5830da0142f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'duel', 'user', ['winner_id'], ['id'])
    op.create_foreign_key(None, 'duel', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'duel', 'user', ['join_id'], ['id'])
    op.add_column('user', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('verification_expire', sa.DateTime(), nullable=True))
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('user', 'verification_expire')
    op.drop_column('user', 'verification_token')
    op.drop_constraint(None, 'duel', type_='foreignkey')
    op.drop_constraint(None, 'duel', type_='foreignkey')
    op.drop_constraint(None, 'duel', type_='foreignkey')
    # ### end Alembic commands ###
